-- Generated by the database client.
CREATE TABLE usuarios(
    id SERIAL NOT NULL,
    username varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    gmail_email varchar(255),
    gmail_password varchar(255),
    gmail_smtp_server varchar(100) DEFAULT 'smtp.gmail.com'::character varying,
    gmail_smtp_port integer DEFAULT 587,
    gmail_ssl_enabled boolean DEFAULT true,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX usuarios_username_key ON public.usuarios USING btree (username);

-- Generated by the database client.
CREATE TABLE listas(
    id SERIAL NOT NULL,
    nombre text NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX listas_nombre_key ON public.listas USING btree (nombre);

-- Generated by the database client.
CREATE TABLE envios(
    id SERIAL NOT NULL,
    fecha timestamp without time zone NOT NULL,
    asunto text NOT NULL,
    cuerpo text NOT NULL,
    usuario_id integer NOT NULL DEFAULT 1,
    lista_id integer NOT NULL DEFAULT 1,
    total_correos integer DEFAULT 0,
    correos_enviados integer DEFAULT 0,
    correos_rebotados integer DEFAULT 0,
    correos_abiertos integer DEFAULT 0,
    estado varchar(20) DEFAULT 'pendiente'::character varying,
    fecha_inicio timestamp without time zone,
    fecha_fin timestamp without time zone,
    error_message text,
    PRIMARY KEY(id),
    CONSTRAINT envios_lista_id_fkey FOREIGN key(lista_id) REFERENCES listas(id),
    CONSTRAINT envios_usuario_id_fkey FOREIGN key(usuario_id) REFERENCES usuarios(id)
);
CREATE INDEX idx_envios_usuario_fecha ON public.envios USING btree (usuario_id, fecha);


-- Generated by the database client.
CREATE TABLE correos(
    id SERIAL NOT NULL,
    email text NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX correos_email_key ON public.correos USING btree (email);

-- Generated by the database client.
CREATE TABLE correos_rebotados(
    id SERIAL NOT NULL,
    envio_id integer NOT NULL,
    correo_id integer NOT NULL,
    fecha_rebote timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    motivo_rebote text,
    codigo_error varchar(10),
    PRIMARY KEY(id),
    CONSTRAINT correos_rebotados_correo_id_fkey FOREIGN key(correo_id) REFERENCES correos(id),
    CONSTRAINT correos_rebotados_envio_id_fkey FOREIGN key(envio_id) REFERENCES envios(id)
);
CREATE INDEX idx_correos_rebotados_envio ON public.correos_rebotados USING btree (envio_id);

-- Generated by the database client.
CREATE TABLE tracking_aperturas(
    id SERIAL NOT NULL,
    envio_id integer NOT NULL,
    correo_id integer NOT NULL,
    fecha_apertura timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address varchar(45),
    user_agent text,
    PRIMARY KEY(id),
    CONSTRAINT tracking_aperturas_correo_id_fkey FOREIGN key(correo_id) REFERENCES correos(id),
    CONSTRAINT tracking_aperturas_envio_id_fkey FOREIGN key(envio_id) REFERENCES envios(id)
);
CREATE INDEX idx_tracking_aperturas_envio ON public.tracking_aperturas USING btree (envio_id);

-- Generated by the database client.
CREATE TABLE correos_listas(
    correo_id integer NOT NULL,
    lista_id integer NOT NULL,
    PRIMARY KEY(correo_id,lista_id),
    CONSTRAINT correos_listas_correo_id_fkey FOREIGN key(correo_id) REFERENCES correos(id),
    CONSTRAINT correos_listas_lista_id_fkey FOREIGN key(lista_id) REFERENCES listas(id)
);


-- Generated by the database client.
CREATE TABLE envios_detalle(
    id SERIAL NOT NULL,
    envio_id integer NOT NULL,
    correo_id integer NOT NULL,
    fecha_envio timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado varchar(20) DEFAULT 'enviado'::character varying,
    mensaje_error text,
    tracking_token varchar(100),
    PRIMARY KEY(id),
    CONSTRAINT envios_detalle_correo_id_fkey FOREIGN key(correo_id) REFERENCES correos(id),
    CONSTRAINT envios_detalle_envio_id_fkey FOREIGN key(envio_id) REFERENCES envios(id)
);
CREATE UNIQUE INDEX envios_detalle_tracking_token_key ON public.envios_detalle USING btree (tracking_token);
CREATE INDEX idx_envios_detalle_envio ON public.envios_detalle USING btree (envio_id);
CREATE INDEX idx_tracking_aperturas_token ON public.envios_detalle USING btree (tracking_token);